### ISSUE TITLE
Character error and Missing -

### ISSUE THREAD

**Issue by runluke** [aws-samples/automate-cross-account-cicd-cfn-cdk#1]
https://github.com/aws-samples/automate-cross-account-cicd-cfn-cdk/blob/0a458aa19dd4867f993edb2b765f30820aeb556a/scripts/automate_deployment.sh#L76

This should be --
Also make sure the first '-' is the right character.  

Error message:
npm ERR! arg Argument starts with non-ascii dash, this is probably invalid: —-profile

**Comment by natalie-white-aws** [comment]
Thanks for finding this! Just pushed the fix. :)
